# Entrega 2 Analisis de bases de Datos

Lo que se quiere hacer inicialmente es un analisis y reduccion de dimension de la base de datos de Matriculados.  
Así que primero caractericemos esta base: 

In [2]:
import pandas as pd
import numpy as np
import seaborn as sns
from matplotlib import pyplot as plt


A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.1.3 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/willgm/.local/lib/python3.10/site-packages/ipykernel_launcher.py", line 18, in <module>
    app.launch_new_instance()
  File "/home/willgm/.local/lib/python3.10/site-packages/traitlets/config/application.py", line 1075, in launch_instance
    app.start()
  File "/home/willgm/.local/lib/python3.10/site-pac

AttributeError: _ARRAY_API not found

ImportError: numpy.core.multiarray failed to import

In [3]:
matriculados = pd.read_csv("/home/willgm/STUFF/UNAL/7sem/Analisis BBDD/Proyecto-ABD-2024-2/Estudiantes_matriculados.csv")

## Caracterizacion de la Base de Datos Original de Matriculados

Los 44 atributos de la base son los siguientes y corresponden a la siguiente informacion:

+ **YEAR:**  
+ **SEMESTRE:**  
+ **TIPO_NIVEL:**          
+ **NIVEL:**  
+ **DEP_NAC:**  
+ **COD_DEP_NAC:**  
+ **CIU_NAC:**  
+ **COD_CIU_NAC:**  
+ **LON_CIU_NAC:**  
+ **LAT_CIU_NAC:**  
+ **DEP_PROC:**  
+ **COD_DEP_PROC:**  
+ **CIU_PROC:**  
+ **COD_CIU_PROC:**  
+ **LON_CIU_PROC:**  
+ **LAT_CIU_PROC:**  
+ **CODS_NAC:**  
+ **CODN_NAC:**  
+ **NACIONALIDAD:**  
+ **EDAD:**  
+ **SEXO:**  
+ **ESTRATO:**  
+ **TIPO_COL:**  
+ **PBM:**  
+ **MAT_PVEZ:**  
+ **SNIES_SEDE_ADM:**  
+ **SEDE_NOMBRE_ADM:**  
+ **SNIES_SEDE_MAT:**  
+ **SEDE_NOMBRE_MAT:**  
+ **ADM_PEAMA_ANDINA**  
+ **MOD_ADM:**  
+ **TIPO_ADM:**  
+ **PAES:**  
+ **PEAMA:**  
+ **MOV_PEAMA:**  
+ **CONVENIO:**  
+ **TIP_CONVENIO:**  
+ **FACULTAD:**  
+ **SNIES_PROGRA:**  
+ **PROGRAMA:**  
+ **AREAC_SNIES:**  
+ **CA_CINE:**  
+ **CD_CINE:**  
+ **AREA_CINE:**  

Estos atributos pueden agruparse de la siguiente manera:  

+ ***NIVEL:*** En esta categoria corresponden *TIPO_NIVEL* y *Nivel*. Pues la primera solo indica que si el estudiante pertenece a pregrado o postgrado,
  la segunda hace lo mismo pero tiene ademas como posibles datos 'Maestria'.'Especializacion','Doctorado','Especializaciones medicas' y 'Pregrado' .  
  Con lo cual podemos tomar unicamente *Nivel*, pues si un estudiante no esta haciendo pregrado y tiene otro Nivel es porque esta haciendo postgrado.  
  Dicho de otra manera, 'NIVEL' determina a 'TIPO_NIVEL'

In [3]:
matriculados['TIPO_NIVEL'].unique()

array(['Pregrado', 'Postgrado'], dtype=object)

In [4]:
matriculados['NIVEL'].unique()

array(['Pregrado', 'Maestría', 'Especialidades médicas',
       'Especialización', 'Doctorado'], dtype=object)

+ ***DEPARTAMENTO DE NACIMIENTO:*** A Esta categoria pertenecen *DEP_NAC* y *COD_DEP_NAC*, pues ambos se determinan entre sí, sabiendo el codigo se puede saber el departemento y viceversa.  

In [12]:
matriculados["DEP_NAC"].unique()

array(['BOGOTÁ, D. C.', 'CUNDINAMARCA', 'META', 'Sin información',
       'HUILA', 'CALDAS', 'GUAINÍA', 'NARIÑO', 'BOYACÁ', 'TOLIMA',
       'SANTANDER', 'NORTE DE SANTANDER', 'PUTUMAYO', 'BOLÍVAR',
       'VALLE DEL CAUCA', 'ARAUCA', 'GUAVIARE', 'CASANARE', 'QUINDÍO',
       'ANTIOQUIA', 'VICHADA', 'CAQUETÁ', 'ATLÁNTICO', 'CESAR',
       'AMAZONAS', 'CAUCA',
       'ARCHIPIÉLAGO DE SAN ANDRÉS, PROVIDENCIA Y SANTA CATALINA',
       'MAGDALENA', 'LA GUAJIRA', 'RISARALDA', 'CÓRDOBA', 'SUCRE',
       'VAUPÉS', 'CHOCÓ'], dtype=object)

In [11]:
matriculados["COD_DEP_NAC"].unique()

array([ 11,  25,  50, -89,  41,  17,  94,  52,  15,  73,  68,  54,  86,
        13,  76,  81,  95,  85,  63,   5,  99,  18,   8,  20,  91,  19,
        88,  47,  44,  66,  23,  70,  97,  27])

+ ***MUNICIPIO*** A esta categoria pertenece *CIU_NAC*, *COD_CIU_NAC*, *LON_CIU_NAC* y *LAT_CIU_NAC*. Si se conoce el municipio del que proviene un estudiantes se conoce un codigo y su latidu y longitud. 

In [13]:
matriculados["CIU_NAC"].unique()

array(['BOGOTÁ, D.C.', 'FACATATIVÁ', 'VILLAVICENCIO', 'Sin información',
       'NEIVA', 'MANIZALES', 'INÍRIDA', 'IPIALES', 'DUITAMA', 'IBAGUÉ',
       'CHÍA', 'UBALÁ', 'MANZANARES', 'SOATÁ', 'TUNJA', 'ARMERO GUAYABAL',
       'GIRARDOT', 'ALDANA', 'BUCARAMANGA', 'CÚCUTA', 'COLÓN', 'PITALITO',
       'SOGAMOSO', 'VILLA DE SAN DIEGO DE UBATÉ', 'ACACÍAS', 'GACHETÁ',
       'SANTA ROSA DEL SUR', 'SUCRE', 'SOACHA', 'CALI', 'PASTO',
       'PALMIRA', 'CHOACHÍ', 'COLOMBIA', 'MARQUETALIA',
       'SAN PABLO DE BORBUR', 'ARAUCA', 'TASCO', 'CHAPARRAL',
       'SAN JOSÉ DEL GUAVIARE', 'SAN FRANCISCO', 'ZIPAQUIRÁ', 'PAIPA',
       'CHIQUINQUIRÁ', 'YOPAL', 'AQUITANIA', 'ARMENIA', 'MEDELLÍN',
       'LA VEGA', 'COTA', 'PUERTO CARREÑO', 'FLORENCIA', 'GUADUAS',
       'BARRANQUILLA', 'GIGANTE', 'MALLAMA', 'CAUCASIA',
       'CARTAGENA DE INDIAS', 'VALLEDUPAR', 'LETICIA', 'ARBELÁEZ',
       'SUSACÓN', 'MADRID', 'TARQUI', 'ALGECIRAS', 'VILLETA',
       'FUSAGASUGÁ', 'SUBACHOQUE', 'AGUAZUL', 'VILLA DE L

In [14]:
matriculados["COD_CIU_NAC"].unique()

array([11001, 25269, 50001, ..., 25258, 54261, 15696])

In [15]:
matriculados["LON_CIU_NAC"].unique()

array([-74.11391872, -74.35101469, -73.6268779 , ..., -74.29016259,
       -72.60393412, -73.60418204])

In [16]:
matriculados["LAT_CIU_NAC"].unique()

array([4.62457505, 4.81224201, 4.12295758, ..., 5.24908341, 7.9370731 ,
       5.71227372])

+ ***DEPARTAMENTO PROCEDIMIENTO***  

In [17]:
matriculados["DEP_PROC"].unique()

array(['BOGOTÁ, D. C.', 'CUNDINAMARCA', 'META', 'HUILA',
       'Sin información', 'NARIÑO', 'BOYACÁ', 'TOLIMA', 'CALDAS',
       'VALLE DEL CAUCA', 'NORTE DE SANTANDER', 'PUTUMAYO', 'BOLÍVAR',
       'SANTANDER', 'CASANARE', 'GUAVIARE', 'ATLÁNTICO', 'ARAUCA',
       'CAQUETÁ', 'AMAZONAS', 'SUCRE',
       'ARCHIPIÉLAGO DE SAN ANDRÉS, PROVIDENCIA Y SANTA CATALINA',
       'QUINDÍO', 'CESAR', 'MAGDALENA', 'LA GUAJIRA', 'CÓRDOBA', 'CAUCA',
       'ANTIOQUIA', 'RISARALDA', 'VAUPÉS', 'VICHADA', 'GUAINÍA', 'CHOCÓ'],
      dtype=object)

In [18]:
matriculados["COD_DEP_PROC"].unique()

array([ 11,  25,  50,  41, -89,  52,  15,  73,  17,  76,  54,  86,  13,
        68,  85,  95,   8,  81,  18,  91,  70,  88,  63,  20,  47,  44,
        23,  19,   5,  66,  97,  99,  94,  27])

+ ***MUNICIPIO PROCEDIMIENTO***  

In [23]:
matriculados["CIU_PROC"].unique()

array(['BOGOTÁ, D.C.', 'FACATATIVÁ', 'VILLAVICENCIO', 'NEIVA',
       'Sin información', 'IPIALES', 'DUITAMA', 'IBAGUÉ',
       'VILLA DE LEYVA', 'CHÍA', 'UBALÁ', 'SOACHA', 'MARQUETALIA',
       'TOCANCIPÁ', 'TUNJA', 'CAMPOHERMOSO', 'MOSQUERA', 'CAJICÁ',
       'ALDANA', 'CALI', 'CÚCUTA', 'COLÓN', 'PITALITO', 'SOGAMOSO',
       'ORITO', 'SANTA ROSA DEL SUR', 'SUCRE', 'TABIO', 'PASTO',
       'PUENTE NACIONAL', 'MONTERREY', 'RÁQUIRA', 'YOPAL', 'CHAPARRAL',
       'SAN MARTÍN', 'SAN JOSÉ DEL GUAVIARE', 'VALLE DEL GUAMUEZ',
       'ZIPAQUIRÁ', 'PAIPA', 'COTA', 'BARRANQUILLA', 'GUASCA', 'ARAUCA',
       'AQUITANIA', 'NOCAIMA', 'FLORENCIA', 'GIGANTE', 'FUNZA', 'MALLAMA',
       'LETICIA', 'SUSACÓN', 'SAN MARCOS', 'MADRID', 'TARQUI', 'SAN LUIS',
       'CARMEN DE APICALÁ', 'CANTAGALLO', 'SUBACHOQUE', 'PAMPLONA',
       'PALERMO', 'SAN ANDRÉS DE TUMACO', 'SIBATÉ', 'CHINAVITA',
       'BUCARAMANGA', 'MÁLAGA', 'SIBUNDOY', 'VERGARA', 'LA ARGENTINA',
       'CONTADERO', 'SAN ANDRÉS', 'MANIZALES',

In [24]:
matriculados["COD_CIU_PROC"].unique()

array([11001, 25269, 50001, 41001,   -89, 52356, 15238, 73001, 15407,
       25175, 25839, 25754, 17444, 25817, 15001, 15135, 25473, 25126,
       52022, 76001, 54001, 86219, 41551, 15759, 86320, 13688, 68773,
       25785, 52001, 68572, 85162, 15600, 85001, 73168, 50689, 95001,
       86865, 25899, 15516, 25214,  8001, 25322, 81001, 15047, 25491,
       18001, 41306, 25286, 52435, 91001, 15774, 70708, 25430, 41791,
       73678, 73148, 13160, 25769, 54518, 41524, 52835, 25740, 15172,
       68001, 68432, 86749, 25862, 41378, 52210, 88001, 17001, 25295,
       25843, 52323, 52320, 15097, 68077, 68276, 25290, 25151, 25799,
       68397, 25718, 73411, 73319, 25873, 15272, 63302, 20045, 15804,
       47555, 25758, 13001, 13430, 44430, 25099, 25053, 86885, 41396,
       25200, 68861, 23417, 13873, 70001, 23001, 47245, 76109, 19212,
       81794, 15837, 52838, 17380,  5001, 54498, 17614, 19001, 23555,
       68425, 63001, 25279, 25307, 76520,  5308, 85015, 20011, 52540,
       25658, 25181,

In [25]:
matriculados["LON_CIU_PROC"].unique()

array([-74.11391872, -74.35101469, -73.6268779 , -75.27794587,
       -89.        , -77.64609566, -73.03026863, -75.19635015,
       -73.52644551, -74.04964819, -73.53230677, -74.19490154,
       -75.04785397, -73.91174581, -73.35436382, -73.10351821,
       -74.22826847, -74.02363653, -77.70037482, -76.5263912 ,
       -72.50559097, -76.96898003, -76.04040041, -72.9232369 ,
       -76.88020986, -74.05144607, -73.79149045, -74.09847546,
       -77.27826745, -73.67750975, -72.88909564, -73.63228856,
       -72.39379053, -75.48358221, -73.69597218, -72.640096  ,
       -76.90503951, -73.99240307, -73.11674378, -74.10293364,
       -74.81878809, -73.87806905, -70.76277305, -72.88435052,
       -74.37747361, -75.60799327, -75.54572948, -74.2019794 ,
       -77.86465833, -69.94067983, -72.68978803, -75.13902232,
       -74.26675545, -75.8267662 , -75.09587039, -74.72333124,
       -73.92442804, -74.17223596, -72.64821106, -75.43278509,
       -78.78940097, -74.25874939, -73.36862894, -73.13

In [26]:
matriculados["LAT_CIU_PROC"].unique()

array([  4.62457505,   4.81224201,   4.12295758,   2.93554559,
       -89.        ,   0.82903172,   5.81936914,   4.43963073,
         5.63623796,   4.86580207,   4.74817719,   4.58639002,
         5.2986509 ,   4.96514275,   5.53937064,   5.03063005,
         4.71430463,   4.92087291,   0.8822436 ,   3.40638218,
         7.90526712,   1.19200058,   1.85414505,   5.72486205,
         0.67602048,   7.9631911 ,   5.91903258,   4.91641735,
         1.2128086 ,   5.87819149,   4.87941197,   5.53873794,
         5.33249118,   3.72576111,   3.70161053,   2.5704781 ,
         0.42390514,   5.02348294,   5.7804891 ,   4.80870097,
        10.97964939,   4.86754875,   7.0777365 ,   5.51831039,
         5.06941561,   1.61582908,   2.38783134,   4.70865654,
         1.14084162,  -4.21202317,   6.23077474,   8.66403585,
         4.7328452 ,   2.10954162,   4.13388115,   4.14664309,
         7.37289896,   4.928374  ,   7.37519415,   2.88665882,
         1.75029972,   4.48787134,   5.16741663,   7.12

+ ***NACIONALIDAD***

In [7]:
print(len(matriculados["CODN_NAC"].unique()))
matriculados["CODS_NAC"].unique()

50


array(['COL', 'BRA', 'Sin información', 'ECU', 'VEN', 'FRA', 'PER', 'PRK',
       'NLD', 'CUB', 'ESP', 'CHE', 'DEU', 'ARG', 'PAN', 'MEX', 'CMR',
       'PRY', 'USA', 'JPN', 'BOL', 'SYR', 'TUR', 'CRI', 'COD', 'NOR',
       'PRI', 'CAN', 'ITA', 'DOM', 'CHN', 'IRN', 'CHL', 'SWE', 'SLV',
       'GTM', 'RUS', 'KOR', 'ISR', 'GBR', 'HND', 'UKR', 'ABW', 'KEN',
       'IND', 'ANT', 'TUN', 'NZL', 'NIC', 'POL'], dtype=object)

In [8]:
print(len(matriculados["CODN_NAC"].unique()))
matriculados["CODN_NAC"].unique()

50


array([170,  76, -89, 218, 862, 250, 604, 408, 528, 192, 724, 756, 276,
        32, 591, 484, 120, 600, 840, 392,  68, 760, 792, 188, 180, 578,
       630, 124, 380, 214, 156, 364, 152, 752, 222, 320, 643, 410, 376,
       826, 340, 804, 533, 404, 356, 530, 788, 554, 558, 616])

In [22]:
matriculados["NACIONALIDAD"].unique()

array(['Colombiana', 'Extranjero', 'Sin información'], dtype=object)

Se puede Reducir a  CODS_NAC o CODS_NAC

+ ***SEDE ADMISION***  

In [28]:
matriculados["SNIES_SEDE_ADM"].unique()

array([1101, 1125, 1124, 1126, 9920, 1102, 1103, 1104, 9933])

In [27]:
matriculados["SEDE_NOMBRE_ADM"].unique()

array(['Bogotá', 'Amazonía', 'Orinoquía', 'Caribe', 'Tumaco', 'Medellín',
       'Manizales', 'Palmira', 'De La Paz'], dtype=object)

+ ***SEDE MATRICULADO***  

In [29]:
matriculados["SNIES_SEDE_MAT"].unique()

array([1101, 1124, 1126, 9920, 1125, 1102, 1103, 1104, 9933])

In [30]:
matriculados["SEDE_NOMBRE_MAT"].unique()

array(['Bogotá', 'Orinoquía', 'Caribe', 'Tumaco', 'Amazonía', 'Medellín',
       'Manizales', 'Palmira', 'De La Paz'], dtype=object)

+ ***TIPO DE ADMISION*** Aqui pertenecen *MOD_ADM* y *TIPO_ADM* , pues si se conoce el tipo de admision (REgular,PAES,Peama,PEAA) se conoce si el modo de admision fuue regular o Especial. 

In [34]:
matriculados["MOD_ADM"].unique()

array(['Regular', 'Especial'], dtype=object)

In [35]:
matriculados["TIPO_ADM"].unique()

array(['Regular', 'PAES', 'PEAMA'], dtype=object)

In [37]:
matriculados["PAES"].unique()

array(['No aplica', 'Comunidades indígenas', 'Mejores bachilleres',
       'Población afrocolombiana',
       'Mejores bachilleres de municipios pobres',
       'Victimas del conflicto armado interno en Colombia', 'De La Paz'],
      dtype=object)

In [36]:
matriculados["PEAMA"].unique()

array(['No aplica', 'PEAMA - Amazonía', 'PEAMA - Orinoquía',
       'PEAMA - Caribe', 'PEAMA - Tumaco',
       'PEAMA - Sede Bogotá - Sumapaz', 'PEAMA - Medellín - Sinifaná',
       'PEAMA - Sede Manizales - Caldas'], dtype=object)

In [38]:
matriculados["MOV_PEAMA"].unique()

array(['No aplica', 'Etapa de movilidad', 'Etapa Inicial'], dtype=object)

In [32]:
matriculados["CONVENIO"].unique()

array(['No aplica', 'No', 'Sí'], dtype=object)

In [33]:
matriculados["TIP_CONVENIO"].unique()

array(['No aplica', 'Externo', 'Interno'], dtype=object)

In [39]:
matriculados["FACULTAD"].unique()

array(['Ingeniería', 'Derecho, ciencias políticas y sociales',
       'Ciencias económicas', 'Ciencias',
       'Medicina veterinaria y de zootecnia', 'Artes', 'Ciencias humanas',
       'Medicina', 'Odontología', 'Ciencias agrarias', 'Enfermería',
       'Arquitectura', 'Minas', 'Ciencias humanas y económicas',
       'Ingeniería y arquitectura', 'Administración',
       'Ciencias exactas y naturales', 'Ciencias agropecuarias',
       'Ingeniería y administración', 'Amazonía', 'Caribe',
       'Escuela de pregrado'], dtype=object)

In [41]:
matriculados["SNIES_PROGRA"].unique()

array([    24,     17,     18,     36,     35,     27,  16940,     25,
       106661,  16941,      3,     29,      6,     14,      9,      5,
           28,     11,  16939, 106654,     31,      1,     15,      8,
        16895,      4,     30,     10,     16,     37,   3140,      2,
           19,      7,   2497,     13,   3103,     32,     20,  19916,
           33,  19910,     96,     12,     34,    106,     55,  19902,
        19907,  19908,  52740,   2605,    103,  52746,  54036, 106338,
          107,   4063,  52728,     48,  91522,     21,     92,     91,
           88,  52741,  16947,  55147,    105,     89,  52747,   3101,
        17906,  52979,  16891, 101794,  16951, 106674,     70,     23,
        16938,  16889,  52980,  55023,  55150,    104,    100,    111,
        53271,  52742,  19904, 106662,  16950,  16890,  19911,   3102,
        52744,  55148,  51674, 106339,     39,    108,     64,  55129,
         3992,  53270, 106671,  19899,  55124,  20487, 106337,  19915,
      

In [46]:
sorted(matriculados["PROGRAMA"].unique())


['Acción Sin Daño y Construcción de Paz',
 'Acción sin daño y construcción de paz',
 'Actuaria y Finanzas',
 'Actuaria y finanzas',
 'Actuaría y Finanzas',
 'Actuaría y finanzas',
 'Administración',
 'Administración Salud Publica',
 'Administración de Empresas',
 'Administración de Empresas (Diurno)',
 'Administración de Empresas (Nocturno)',
 'Administración de Sistemas Informáticos',
 'Administración de empresas',
 'Administración de empresas (diurno)',
 'Administración de empresas (nocturno)',
 'Administración de la Justicia',
 'Administración de sistemas informáticos',
 'Administración salud publica',
 'Agroecología',
 'Alimentación y Nutrición Promoción de la Salud',
 'Alimentación y nutrición promoción de la salud',
 'Alta Gerencia',
 'Alta gerencia',
 'Analítica',
 'Anatomopatología Veterinaria',
 'Anatomopatología veterinaria',
 'Anestesiología y Reanimación',
 'Anestesiología y reanimación',
 'Animación',
 'Antropología',
 'Análisis Espacial',
 'Análisis de Políticas Públicas'

Note que hay varios nombres repetidos, sin embargo corresponden a carreras en diferentes Sedes

In [ ]:
matriculados["ADM_PEAMA_ANDINA"].unique() #ESTA VA SOLA

In [47]:
matriculados["AREAC_SNIES"].unique()

array(['Ingeniería, arquitectura, urbanismo y afines',
       'Ciencias sociales y humanas',
       'Economía, administración, contaduría y afines',
       'Matemáticas y ciencias naturales',
       'Agronomía, veterinaria y afines', 'Bellas artes',
       'Ciencias de la salud', 'Ciencias de la educación'], dtype=object)

[AREAS SNIES](https://snies.mineducacion.gov.co/portal/DOCUMENTOS/Glosario/)

In [48]:
matriculados["CA_CINE"].unique()

array([8, 4, 3, 5, 7, 6, 2, 9, 1])

In [49]:
matriculados["CD_CINE"].unique()

array([811, 421, 311, 531, 541, 713, 722, 732, 613, 714, 711, 211, 313,
       912, 212, 715, 911, 232, 511, 923, 915, 411, -89, 731, 314, 916,
       312, 841, 413, 913, 213, 222, 542, 223, 929, 533, 532, 588, 231,
       288, 215, 210, 721, 388, 111, 688, 539, 219, 521, 619, 611, 712,
       724, 821, 612, 412, 730])

In [50]:
matriculados["AREA_CINE"].unique()

array(['Agricultura, silvicultura, pesca y veterinaria',
       'Administración de empresas y derecho',
       'Ciencias sociales, periodismo e información',
       'Ciencias naturales, matemáticas y estadística',
       'Ingeniería, industria y construcción',
       'Tecnologías de la información y la comunicación (TIC)',
       'Artes y humanidades', 'Salud y bienestar', 'Educación'],
      dtype=object)

+ ***Categorias Unicas:*** Entre estos se encuentran `Year`,`SEMESTRE`,`EDAD`,`SEXO`,`ESTRATO`,`TIPO_COL`,`PBM`,`MAT_PVEZ`. Pues ninguno se encuentra relacionado con otro atributo

# Limpieza de Datos

## Reduccion de dimensionalidad
Para hacer esto tendremos en cuenta la categorias y los futuros analisis.
Por ejemplo en la categoria departamento de nacimiento unicamente se dejara el atributo de `DEP_NAC` pues ofrece la misma informacion que el codigo.

In [10]:
matriculados.drop(columns=['COD_DEP_NAC'], inplace=True)

 TODO: mirar si se puede unir todos los atributos relativos a admisiones especiales



#_______  
primeramente se va a reducir la dimension de la base de datos de Matriculados, pues a simple vista 
se nota que existen varios atributos que corresponden a la misma información  
