<a href="https://colab.research.google.com/github/10scar/Proyecto-ABD-2024-2/blob/JuanBranch/Entrega.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Entrega 2

In [3]:
import pandas as pd
import numpy as np
import seaborn as sns
from matplotlib import pyplot as plt
graduados = pd.read_csv('Estudiantes_Graduados.csv')

In [4]:
graduados

YEAR  SEMESTRE TIPO_NIVEL            NIVEL        DEP_NAC  COD_DEP_NAC  \
0      2018         1  Postgrado         Maestría  BOGOTÁ, D. C.           11   
1      2018         1  Postgrado  Especialización      ANTIOQUIA            5   
2      2018         1  Postgrado  Especialización  BOGOTÁ, D. C.           11   
3      2018         1  Postgrado  Especialización         BOYACÁ           15   
4      2018         1  Postgrado  Especialización  BOGOTÁ, D. C.           11   
...     ...       ...        ...              ...            ...          ...   
56104  2023         2  Postgrado         Maestría          CESAR           20   
56105  2023         2  Postgrado         Maestría          CESAR           20   
56106  2023         2  Postgrado         Maestría         ARAUCA           81   
56107  2023         2  Postgrado         Maestría  BOGOTÁ, D. C.           11   
56108  2023         2  Postgrado        Doctorado  BOGOTÁ, D. C.           11   

            CIU_NAC  COD_CIU_NAC  LON_CIU_NAC  LAT_CIU_NAC  ...      PEAMA  \
0      BOGOTÁ, D.C.        11001   -74.113919     4.624575  ...  No aplica   
1          MEDELLÍN         5001   -75.577056     6.248941  ...  No aplica   
2      BOGOTÁ, D.C.        11001   -74.113919     4.624575  ...  No aplica   
3          SOGAMOSO        15759   -72.923237     5.724862  ...  No aplica   
4      BOGOTÁ, D.C.        11001   -74.113919     4.624575  ...  No aplica   
...             ...          ...          ...          ...  ...        ...   
56104      CURUMANÍ        20228   -73.541364     9.200340  ...  No aplica   
56105    VALLEDUPAR        20001   -73.258648    10.461518  ...  No aplica   
56106   CRAVO NORTE        81220   -70.203568     6.303394  ...  No aplica   
56107  BOGOTÁ, D.C.        11001   -74.113919     4.624575  ...  No aplica   
56108  BOGOTÁ, D.C.        11001   -74.113919     4.624575  ...  No aplica   

              CONVENIO     TIP_CONVENIO             FACULTAD SNIES_PROGRA  \
0      Sin información  Sin información             Amazonia        19920   
1      Sin información  Sin información             Amazonia        20491   
2      Sin información  Sin información                Artes        52972   
3      Sin información  Sin información                Artes        53263   
4      Sin información  Sin información                Artes        53263   
...                ...              ...                  ...          ...   
56104               Sí          Interno             Medicina           88   
56105               Sí          Interno             Medicina           88   
56106               No        No aplica             Medicina        91522   
56107               No        No aplica  Ciencias económicas         4063   
56108               No        No aplica  Ciencias económicas        19895   

                                             PROGRAMA  \
0                                 Estudios amazónicos   
1                                 Estudios amazónicos   
2                                           Animación   
3                    Diseño y desarrollo del producto   
4                    Diseño y desarrollo del producto   
...                                               ...   
56104                                   Salud Pública   
56105                                   Salud Pública   
56106  Fisioterapia del Deporte y la Actividad Física   
56107                             Ciencias Económicas   
56108                             Ciencias Económicas   

                                         AREAC_SNIES CA_CINE  CD_CINE  \
0                        Ciencias sociales y humanas       3      388   
1                        Ciencias sociales y humanas       3      388   
2                                       Bellas artes       2      211   
3                                       Bellas artes       2      210   
4                                       Bellas artes       2      210   
...                                              

In [24]:
print(graduados.shape)
print(graduados.columns)

(56109, 33)
Index(['YEAR', 'SEMESTRE', 'TIPO_NIVEL', 'NIVEL', 'DEP_NAC', 'COD_DEP_NAC',
       'CIU_NAC', 'COD_CIU_NAC', 'LON_CIU_NAC', 'LAT_CIU_NAC', 'CODS_NAC',
       'CODN_NAC', 'NACIONALIDAD', 'EDAD', 'SEXO', 'ESTRATO', 'SNIES_SEDE_ADM',
       'SEDE_NOMBRE_ADM', 'SNIES_SEDE_MAT', 'SEDE_NOMBRE_MAT', 'MOD_ADM',
       'TIPO_ADM', 'PAES', 'PEAMA', 'CONVENIO', 'TIP_CONVENIO', 'FACULTAD',
       'SNIES_PROGRA', 'PROGRAMA', 'AREAC_SNIES', 'CA_CINE', 'CD_CINE',
       'AREA_CINE'],
      dtype='object')
['BOGOTÁ, D. C.' 'ANTIOQUIA' 'BOYACÁ' 'CAQUETÁ' 'CUNDINAMARCA' 'SUCRE'
 'CALDAS' 'TOLIMA' 'CESAR' 'Sin información' 'NARIÑO' 'QUINDÍO' 'HUILA'
 'CÓRDOBA' 'MAGDALENA' 'CAUCA' 'VALLE DEL CAUCA' 'NORTE DE SANTANDER'
 'ATLÁNTICO' 'RISARALDA' 'CASANARE' 'ARAUCA' 'META' 'SANTANDER' 'BOLÍVAR'
 'VICHADA' 'CHOCÓ'
 'ARCHIPIÉLAGO DE SAN ANDRÉS, PROVIDENCIA Y SANTA CATALINA' 'PUTUMAYO'
 'LA GUAJIRA' 'AMAZONAS' 'GUAVIARE' 'GUAINÍA' 'VAUPÉS'
 'ARCHIPIÉLAGO DE SAN ANDRÉS, PROVIDENCIA Y']


Se tienen 33 atributos, los cuales son:
* YEAR
* SEMESTRE
* TIPO_NIVEL
* NIVEL
* DEP_NAC
* COD_DEP_NAC
* CIU_NAC
* COD_CIU_NAC
* LON_CIU_NAC
* LAT_CIU_NAC
* CODS_NAC
* CODN_NAC
* NACIONALIDAD
* EDAD
* SEXO
* ESTRATO
* SNIES_SEDE_ADM
* SEDE_NOMBRE_ADM
* SNIES_SEDE_MAT
* SEDE_NOMBRE_MAT
* MOD_ADM
* TIPO_ADM
* PAES
* PEAMA
* CONVENIO
* TIP_CONVENIO
* FACULTAD
* SNIES_PROGRA
* PROGRAMA
* AREAC_SNIES
* CA_CINE
* CD_CINE
* AREA_CINE

Vamos a agrupar atributos con información relacionada

## **(I)** Identificación de Departamentos
* DEP_NAC: Nombre del departamento de nacimiento.
* COD_DEP_NAC: Código del departamento de nacimiento.

In [15]:
print("Identificación de Departamentos:")
print(graduados['DEP_NAC'].unique())
print()
print(graduados['COD_DEP_NAC'].unique())

Identificación de Departamentos:
['BOGOTÁ, D. C.' 'ANTIOQUIA' 'BOYACÁ' 'CAQUETÁ' 'CUNDINAMARCA' 'SUCRE'
 'CALDAS' 'TOLIMA' 'CESAR' 'Sin información' 'NARIÑO' 'QUINDÍO' 'HUILA'
 'CÓRDOBA' 'MAGDALENA' 'CAUCA' 'VALLE DEL CAUCA' 'NORTE DE SANTANDER'
 'ATLÁNTICO' 'RISARALDA' 'CASANARE' 'ARAUCA' 'META' 'SANTANDER' 'BOLÍVAR'
 'VICHADA' 'CHOCÓ'
 'ARCHIPIÉLAGO DE SAN ANDRÉS, PROVIDENCIA Y SANTA CATALINA' 'PUTUMAYO'
 'LA GUAJIRA' 'AMAZONAS' 'GUAVIARE' 'GUAINÍA' 'VAUPÉS'
 'ARCHIPIÉLAGO DE SAN ANDRÉS, PROVIDENCIA Y']

[ 11   5  15  18  25  70  17  73  20 -89  52  63  41  23  47  19  76  54
   8  66  85  81  50  68  13  99  27  88  86  44  91  95  94  97]


## **(II)** Identificación de Ciudades
* CIU_NAC: Nombre de la ciudad de nacimiento.
* COD_CIU_NAC: Código de la ciudad de nacimiento.
* LON_CIU_NAC: Longitud de la ciudad de nacimiento.
* LAT_CIU_NAC: Latitud de la ciudad de nacimiento.

In [16]:
print("Identificación de Ciudades:")
print(graduados['CIU_NAC'].unique())
print()
print(graduados['COD_CIU_NAC'].unique())
print()
print(graduados['LON_CIU_NAC'].unique())
print()
print(graduados['LAT_CIU_NAC'].unique())

Identificación de Ciudades:
['BOGOTÁ, D.C.' 'MEDELLÍN' 'SOGAMOSO' 'ZARAGOZA' 'FLORENCIA'
 'CHIQUINQUIRÁ' 'ZIPAQUIRÁ' 'SANTIAGO DE TOLÚ' 'TUNJA' 'GACHALÁ'
 'MANIZALES' 'IBAGUÉ' 'GUASCA' 'DUITAMA' 'VALLEDUPAR' 'Sin información'
 'IPIALES' 'ARMENIA' 'NEIVA' 'SAHAGÚN' 'CALARCÁ' 'SANTA MARTA'
 'VILLARRICA' 'POPAYÁN' 'JAMUNDÍ' 'CÚCUTA' 'SANTA ISABEL' 'CHÍA'
 'SAN BERNARDO' 'PAMPLONA' 'PUERTO COLOMBIA' 'BARRANQUILLA' 'CAIMITO'
 'CALI' 'RIONEGRO' 'ARBELÁEZ' 'GUACHETÁ' 'NOCAIMA' 'PASTO' 'SANTUARIO'
 'SALAMINA' 'FACATATIVÁ' 'MONTERÍA' 'LA PLATA' 'UBALÁ' 'GUATEQUE'
 'VILLANUEVA' 'PRADO' 'LA CEJA' 'SARAVENA' 'VILLAVICENCIO' 'BUGALAGRANDE'
 'GUADUAS' 'SAN JOSÉ DE MIRANDA' 'GARZÓN' 'TOGÜÍ' 'CUÍTIVA' 'SOACHA'
 'BUCARAMANGA' 'ROVIRA' 'VILLA DE SAN DIEGO DE UBATÉ' 'PLANADAS' 'VIOTÁ'
 'MAGANGUÉ' 'SUAZA' 'MIRAFLORES' 'HONDA' 'SOLEDAD' 'LÍBANO' 'SIMIJACA'
 'TABIO' 'CHIMICHAGUA' 'APARTADÓ' 'CHINCHINÁ' 'CARAMANTA' 'QUIPILE'
 'CARTAGENA DE INDIAS' 'SUSACÓN' 'MARIPÍ' 'PEREIRA' 'PUERTO CARREÑO'
 'PUENTE NACION

## **(III)** Información Geográfica General
* CODS_NAC: Código geográfico general de la región.
* CODN_NAC: Código numérico relacionado a la geografía o nacionalidad.
* NACIONALIDAD: Nacionalidad de la persona.

In [ ]:
print("Información Geográfica General:")
print(graduados['CODS_NAC'].unique())
print()
print(graduados['CODN_NAC'].unique())
print()
print(graduados['NACIONALIDAD'].unique())

## **(IV)** Datos Académicos
Administrativos
* SNIES_SEDE_ADM: Código SNIES de la sede administrativa.
* SEDE_NOMBRE_ADM: Nombre de la sede administrativa.

Académicos

* SNIES_SEDE_MAT: Código SNIES de la sede de matrícula.
* SEDE_NOMBRE_MAT: Nombre de la sede de matrícula.
* FACULTAD: Facultad a la que pertenece el estudiante.
* SNIES_PROGRA: Código SNIES del programa académico.
* PROGRAMA: Nombre del programa académico.

In [18]:
# Administrativos
print()
print("===================================")
print("Datos Académicos - Administrativos:")
print("===================================")
print()
print(graduados['SNIES_SEDE_ADM'].unique())
print()
print(graduados['SEDE_NOMBRE_ADM'].unique())
# Académicos
print()
print("==============================")
print("Datos Académicos - Académicos:")
print("==============================")
print()
print(graduados['SNIES_SEDE_MAT'].unique())
print()
print(graduados['SEDE_NOMBRE_MAT'].unique())
print()
print(graduados['FACULTAD'].unique())
print()
print(graduados['SNIES_PROGRA'].unique())
print()
print(graduados['PROGRAMA'].unique())


Datos Académicos - Administrativos:

[1125 1101 1103 1102 1104 1124 1126 9920]

['Amazonía' 'Bogotá' 'Manizales' 'Medellín' 'Palmira' 'Orinoquía' 'Caribe'
 'Tumaco']

Datos Académicos - Académicos:

[1125 1101 1103 1102 1104 1126]

['Amazonía' 'Bogotá' 'Manizales' 'Medellín' 'Palmira' 'Caribe']

['Amazonia' 'Artes' 'Ciencias' 'Ciencias agrarias' 'Ciencias económicas'
 'Ciencias humanas' 'Derecho, ciencias políticas y sociales' 'Enfermería'
 'Ingeniería' 'Medicina' 'Medicina veterinaria y de zootecnia'
 'Odontología' 'Administración' 'Ciencias exactas y naturales'
 'Ingeniería y arquitectura' 'Arquitectura'
 'Ciencias humanas y económicas' 'Minas' 'Ciencias agropecuarias'
 'Ingeniería y administración' 'Amazonía' 'Caribe']

[ 19920  20491  52972  53263  53264 101795  16888  52732  16889  52733
  16890  52734 103552  52976  52746 106675  52744  52741  52742 101798
  52747 106672    103  52727   2604  19892  52728  19893  19894    112
    111 101982 102866  19901   2449   2603    104  19

## **(V)** Información Demográfica
* EDAD: Edad de la persona.
* SEXO: Sexo de la persona.
* ESTRATO: Estrato socioeconómico.

In [ ]:
print("Información Demográfica:")
print(graduados['EDAD'].unique())
print()
print(graduados['SEXO'].unique())
print()
print(graduados['ESTRATO'].unique())

## **(VI)** Información de Admisión
* MOD_ADM: Modalidad de admisión.
* TIPO_ADM: Tipo de admisión.
* PAES: Participación en el programa PAES.
* PEAMA: Participación en el programa PEAMA.
* CONVENIO: Indica si hay un convenio en la admisión.
* TIP_CONVENIO: Tipo de convenio.

In [ ]:
print("Información de Admisión:")
print(graduados['MOD_ADM'].unique())
print()
print(graduados['TIPO_ADM'].unique())
print()
print(graduados['PAES'].unique())
print()
print(graduados['PEAMA'].unique())
print()
print(graduados['CONVENIO'].unique())
print()
print(graduados['TIP_CONVENIO'].unique())

## **(VIII)** Información de Clasificación Académica
* AREAC_SNIES: Área académica según el SNIES.
* CA_CINE: Clasificación CINE-CA del programa.
* CD_CINE: Clasificación CINE-CD del programa.
* AREA_CINE: Nombre del área según la clasificación CINE.

In [ ]:
print("Información de Clasificación Académica:")
print(graduados['AREAC_SNIES'].unique())
print()
print(graduados['CA_CINE'].unique())
print()
print(graduados['CD_CINE'].unique())
print()
print(graduados['AREA_CINE'].unique())

## **(VIII)** Información Temporal
* YEAR: Año de referencia del dato.
* SEMESTRE: Semestre del dato.

In [19]:
print("Información Temporal:")
print(graduados['YEAR'].unique())
print()
print(graduados['SEMESTRE'].unique())

Información Temporal:
[2018 2019 2020 2021 2022 2023]

[1 2]


## Atributos potencialmente irrelevantes o redundantes
* *COD_DEP_NAC*, *COD_CIU_NAC:* Ya se tienen los atributos de nombre departamento y ciudad por lo que el código puede ser redundante
